// 厨房板块：本周菜单 / 冰箱 / 购买清单
import{S,update,uid,today,addDays,mondayOf,fmtDate,weekday,daysUntil,MEALS,PET,toast,addToMenu,removeMenuItem,menuItems,refOf,findRecipe,findDining,logMeal,dayIntake,deductPantry,pantryMatches,expiringItems,lowItems,addPantryHistory,generateShopping}from'./store.js';
import{ico,esc,fileToDataUrl}from'./ui.js';
import{openCategoryEditor}from'./settings.js';

const V=()=>document.querySelector('#view');

// —— 菜单选择器（菜谱 / 零食 / 外出） ——
export function menuAddDialog(date,meal,onDone){const dlg=document.querySelector('#dialog-root');let tab='dish',q='';
dlg.innerHTML=`<div class="editor"><div class="modal-heading"><div><span class="eyebrow">${fmtDate(date)} · ${MEALS.find(m=>m[0]===meal)[1]}</span><h2>添加到菜单</h2></div><button class="icon-button" data-close aria-label="关闭">${ico('close')}</button></div><div class="editor-content"><div class="type-tabs" role="tablist"><button data-tab="dish">烹饪菜</button><button data-tab="snack">零食速食</button><button data-tab="dining">外出就餐</button></div><label class="search">${ico('search',15)}<input id="pick-search" placeholder="搜索名称…"></label><div class="pick-list" id="pick-list"></div></div><div class="modal-footer"><span></span><div><button class="secondary" data-close>取消</button></div></div></div>`;dlg.showModal();
const close=()=>dlg.close();dlg.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);
const list=dlg.querySelector('#pick-list'),search=dlg.querySelector('#pick-search');
const draw=()=>{dlg.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('chosen',b.dataset.tab===tab));
const src=(tab==='dining'?S.dining:S.recipes.filter(r=>r.type===tab)).filter(x=>x.name.toLowerCase().includes(q));
list.innerHTML=src.map(x=>`<button class="pick-item" data-id="${x.id}"><span class="pick-thumb">${x.image?`<img src="${esc(x.image)}" alt="" onerror="this.style.display='none'">`:ico('leaf',16)}</span><span class="pick-info"><strong>${esc(x.name)}</strong><small>${esc(x.category||'')}${x.calories?` · ${x.calories} 千卡/份`:''}</small></span>${ico('plus',16)}</button>`).join('')||'<p class="muted" style="padding:20px">没有匹配的记录</p>';
list.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const ref=tab==='dining'?findDining(b.dataset.id):findRecipe(b.dataset.id);if(!ref)return;update(()=>addToMenu(date,meal,ref));dlg.close();toast(`已把「${ref.name}」加入 ${fmtDate(date)} ${MEALS.find(m=>m[0]===meal)[1]}`);onDone?.()})};
dlg.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;draw()});search.oninput=()=>{q=search.value.toLowerCase();draw()};draw()}

// 先选日期和餐次，再选内容（用于菜谱 / 外出详情页）
export function menuSlotPicker(ref){const dlg=document.querySelector('#dialog-root');const days=Array.from({length:7},(_,i)=>addDays(today(),i));let date=days[0],meal='dinner';
dlg.innerHTML=`<div class="editor"><div class="modal-heading"><div><span class="eyebrow">PLAN A MEAL</span><h2>把「${esc(ref.name)}」排进菜单</h2></div><button class="icon-button" data-close aria-label="关闭">${ico('close')}</button></div><div class="editor-content"><div class="field"><span class="cat-label">选择日期（近 7 天）</span><div class="chips" id="pick-days">${days.map(d=>`<button type="button" class="filter ${d===date?'chosen':''}" data-date="${d}">${fmtDate(d)} 周${weekday(d)}${d===today()?' · 今天':''}</button>`).join('')}</div></div><div class="field"><span class="cat-label">选择餐次</span><div class="chips" id="pick-meals">${MEALS.map(([m,ml])=>`<button type="button" class="filter ${m===meal?'chosen':''}" data-meal="${m}">${ml}</button>`).join('')}</div></div></div><div class="modal-footer"><span></span><div><button class="secondary" data-close>取消</button><button class="primary" id="pick-add">${ico('check')} 加入菜单</button></div></div></div>`;dlg.showModal();
dlg.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dlg.close());
dlg.querySelectorAll('#pick-days [data-date]').forEach(b=>b.onclick=()=>{date=b.dataset.date;dlg.querySelectorAll('#pick-days [data-date]').forEach(x=>x.classList.toggle('chosen',x===b))});
dlg.querySelectorAll('#pick-meals [data-meal]').forEach(b=>b.onclick=()=>{meal=b.dataset.meal;dlg.querySelectorAll('#pick-meals [data-meal]').forEach(x=>x.classList.toggle('chosen',x===b))});
dlg.querySelector('#pick-add').onclick=()=>{update(()=>addToMenu(date,meal,ref));dlg.close();toast(`已加入 ${fmtDate(date)} ${MEALS.find(m=>m[0]===meal)[1]}，可在「本周菜单」查看`)}}

// —— 本周菜单 ——
export function renderWeek(mount){const start=mondayOf(addDays(mondayOf(today()),(renderWeek.offset||0)*7));
const days=Array.from({length:7},(_,i)=>addDays(start,i));
mount.innerHTML=`<section class="intro"><div><div class="eyebrow">THIS WEEK'S TABLE</div><h1>本周，吃点什么？</h1><p>把菜谱、零食和外出安排填进一周格子；吃完点 ✓，自动记录并扣减库存。</p></div><div class="week-nav"><button class="secondary" id="w-prev">‹ 上一周</button><button class="secondary" id="w-today">本周</button><button class="secondary" id="w-next">下一周 ›</button></div></section><div class="week-grid">${['一','二','三','四','五','六','日'].map((w,i)=>{const d=days[i];return`<div class="week-day ${d===today()?'today':''}"><header><strong>周${w}</strong><span>${Number(d.slice(5,7))}/${Number(d.slice(8,10))}</span></header>${MEALS.map(([m,ml])=>`<div class="meal-slot"><div class="meal-head"><span>${ml}</span><button class="icon-button" data-add="${d}|${m}" aria-label="添加${ml}">${ico('plus',13)}</button></div>${menuItems(d,m).map((item,idx)=>`<div class="menu-item ${item.done?'done':''}"><button class="item-done" data-done="${d}|${m}|${idx}" aria-label="标记完成" aria-pressed="${!!item.done}">${ico('check',12)}</button><span class="item-name" title="${esc(item.name)}">${esc(item.name)}</span><button class="icon-button" data-remove="${d}|${m}|${idx}" aria-label="移除">${ico('close',12)}</button></div>`).join('')||'<span class="meal-empty">未安排</span>'}</div>`).join('')}</div>`}).join('')}</div><p class="muted week-tip">本周已记录 ${days.reduce((n,d)=>n+(S.log[d]?.length||0),0)} 餐 · 今日摄入 ${dayIntake(today())} 千卡</p>`;
mount.querySelector('#w-prev').onclick=()=>{renderWeek.offset=(renderWeek.offset||0)-1;renderWeek(V())};mount.querySelector('#w-next').onclick=()=>{renderWeek.offset=(renderWeek.offset||0)+1;renderWeek(V())};mount.querySelector('#w-today').onclick=()=>{renderWeek.offset=0;renderWeek(V())};
mount.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const[d,m]=b.dataset.add.split('|');menuAddDialog(d,m,()=>renderWeek(V()))});
mount.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const[d,m,i]=b.dataset.remove.split('|');update(()=>removeMenuItem(d,m,Number(i)));renderWeek(V())});
mount.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{const[d,m,i]=b.dataset.done.split('|');const item=menuItems(d,m)[Number(i)];if(!item)return;
if(!item.done){const r=refOf(item);const ings=r&&r.type!=='dining'?(r.ingredients||[]).map(x=>({name:x.name,amount:x.amount,match:pantryMatches(x.name)[0]})).filter(x=>x.match):[];let deduct=true;
if(ings.length){deduct=window.confirm(`记录「${item.name}」已做完，并从冰箱扣减：\n${ings.map(x=>`· ${x.match.name}（扣 ${x.amount||'1'}）`).join('\n')}\n\n确定吗？「取消」则只记录不扣库存。`)}
update(()=>{item.done=true;logMeal(d,m,r||{name:item.name,calories:0});if(deduct)ings.forEach(x=>deductPantry(x.name,x.amount))});toast(deduct&&ings.length?'已记录，库存已扣减':'已记录到当天')}else{update(()=>{item.done=false;if(S.log[d]){S.log[d]=S.log[d].filter(e=>!(e.refId===item.refId&&e.name===item.name));if(!S.log[d].length)delete S.log[d]}});toast('已取消记录（库存扣减不回退）')}renderWeek(V())})}

// —— 冰箱 ——
export function renderFridge(mount){const exp=expiringItems(),low=lowItems();
const groups=[...new Set([...S.cats.fridge,...S.pantry.map(p=>p.category)])].filter(c=>S.pantry.some(p=>p.category===c));
mount.innerHTML=`<section class="intro"><div><div class="eyebrow">INSIDE THE FRIDGE</div><h1>冰箱里有什么？</h1><p>记录库存、生产日期和保质期，快过期会提醒你；猫狗能不能吃也标出来。</p></div><div class="detail-tools"><button class="text-button" id="manage-cats">${ico('settings',15)} 分类</button><button class="primary" id="add-food">${ico('plus')} 添加食材</button></div></section>${exp.length?`<div class="warn-banner">${ico('bell',18)}<div><strong>${exp.length} 项食材临期或已过期</strong><span>${exp.slice(0,3).map(p=>`${esc(p.name)}（${daysUntil(p.expiryDate)<0?'已过期':daysUntil(p.expiryDate)===0?'今天到期':daysUntil(p.expiryDate)+'天后到期'}）`).join('、')}${exp.length>3?' 等':''}</span></div><button class="text-button" id="see-rec">${ico('sparkle',15)} 看推荐</button></div>`:''}<div class="fridge-list">${S.pantry.slice().sort((a,b)=>daysUntil(a.expiryDate)-daysUntil(b.expiryDate)).map(item=>{const dv=daysUntil(item.expiryDate);const info=dv<0?{label:`已过期 ${-dv} 天`,cls:'expired'}:dv<=2?{label:dv===0?'今天到期':`${dv} 天后到期`,cls:'soon'}:{label:`剩 ${dv} 天`,cls:'fresh'};const lowBadge=item.lowAt&&Number(item.qty)<=Number(item.lowAt);return`<div class="food-row ${info.cls==='expired'?'row-expired':''}"><div class="food-main"><strong>${esc(item.name)}</strong><span class="food-meta">${esc(item.category)} · ${esc(item.prodDate||'—')} 生产 · ${esc(item.expiryDate||'—')} 到期${item.notes?` · ${esc(item.notes)}`:''}</span><div class="food-badges"><span class="badge ${info.cls}">${info.label}</span>${lowBadge?'<span class="badge low">余量不足</span>':''}${petBadge('🐱',item.petCat)}${petBadge('🐶',item.petDog)}</div></div><div class="food-qty"><button class="qty-btn" data-deduct="${item.id}" aria-label="减少库存">−</button><strong>${esc(item.qty)}</strong><small>${esc(item.unit)}</small><button class="qty-btn" data-restock="${item.id}" aria-label="增加库存">＋</button></div><div class="food-tools"><button class="icon-button" data-edit="${item.id}" aria-label="编辑">${ico('edit',15)}</button><button class="icon-button" data-del="${item.id}" aria-label="删除">${ico('trash',15)}</button></div></div>`}).join('')||`<div class="empty" style="grid-column:1/-1"><div>${ico('fridge')}</div><h3>冰箱是空的</h3><p>点击「添加食材」记录第一批库存。</p></div>`}</div>${low.length?`<p class="muted">低库存提醒：${low.map(p=>esc(p.name)).join('、')}</p>`:''}`;
mount.querySelector('#manage-cats').onclick=()=>openCategoryEditor();
mount.querySelector('#add-food').onclick=()=>foodDialog(null);
mount.querySelector('#see-rec')?.addEventListener('click',()=>location.hash='#/recommend');
mount.querySelectorAll('[data-deduct]').forEach(b=>b.onclick=()=>{update(()=>{const p=S.pantry.find(x=>x.id===b.dataset.deduct);p.qty=Math.max(0,(Number(p.qty)||0)-1)});renderFridge(V())});
mount.querySelectorAll('[data-restock]').forEach(b=>b.onclick=()=>{update(()=>{const p=S.pantry.find(x=>x.id===b.dataset.restock);p.qty=(Number(p.qty)||0)+1});renderFridge(V())});
mount.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>foodDialog(S.pantry.find(x=>x.id===b.dataset.edit)));
mount.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(window.confirm('确定删除这条库存？')){update(()=>S.pantry=S.pantry.filter(x=>x.id!==b.dataset.del));renderFridge(V())}})}
function petBadge(icon,v){if(!v||v==='na')return'';return`<span class="badge pet-${v}">${icon} ${PET[v]}</span>`}

export function foodDialog(item){const dlg=document.querySelector('#dialog-root');const isNew=!item;
dlg.innerHTML=`<form id="food-form" class="editor"><div class="modal-heading"><div><span class="eyebrow">STOCK IT UP</span><h2>${isNew?'添加食材':'编辑食材'}</h2></div><button type="button" class="icon-button" data-close aria-label="关闭">${ico('close')}</button></div><div class="editor-content">${S.pantryHistory.length?`<div class="field"><span class="cat-label">最近添加 · 点击带出保质期等信息</span><div class="chips">${S.pantryHistory.slice(0,8).map(h=>`<button type="button" class="filter" data-quick="${esc(h.name)}">${esc(h.name)}</button>`).join('')}</div></div>`:''}<label class="field">名称 <span class="required">*</span><input name="name" required maxlength="40" placeholder="例如：鸡蛋" value="${esc(item?.name||'')}"></label><div class="field-row"><label class="field">分类<select name="category">${S.cats.fridge.map(c=>`<option ${item?.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label class="field">数量<input name="qty" type="number" min="0" step="0.5" value="${item?.qty??1}"></label><label class="field">单位<input name="unit" maxlength="6" value="${esc(item?.unit||'个')}"></label></div><div class="field-row"><label class="field">生产日期<input name="prodDate" type="date" value="${esc(item?.prodDate||today())}"></label><label class="field">保质期（天）<input name="shelf" type="number" min="1" max="9999" value="${item?Math.max(1,Math.round((Date.parse(item.expiryDate+'T00:00:00')-Date.parse((item.prodDate||today())+'T00:00:00'))/86400000)):7}"></label><label class="field">低量提醒<input name="lowAt" type="number" min="0" step="0.5" placeholder="低于此数量提醒" value="${item?.lowAt??''}"></label></div><div class="field-row"><label class="field">🐱 猫<select name="petCat">${['na','ok','care','no'].map(v=>`<option value="${v}" ${item?.petCat===v?'selected':''}>${PET[v]}</option>`).join('')}</select></label><label class="field">🐶 狗<select name="petDog">${['na','ok','care','no'].map(v=>`<option value="${v}" ${item?.petDog===v?'selected':''}>${PET[v]}</option>`).join('')}</select></label></div><label class="field">备注<input name="notes" maxlength="80" placeholder="例如：煮熟后可少量喂" value="${esc(item?.notes||'')}"></label></div><div class="modal-footer">${isNew?'<span class="muted">记录一次，下次一键带出。</span>':'<span></span>'}<div><button type="button" class="secondary" data-close>取消</button><button type="submit" class="primary">${ico('check')} 保存</button></div></div></form>`;dlg.showModal();
dlg.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dlg.close());
dlg.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{const h=S.pantryHistory.find(x=>x.name===b.dataset.quick);if(!h)return;const f=dlg.querySelector('#food-form');f.name.value=h.name;f.category.value=h.category;f.unit.value=h.unit;f.shelf.value=h.shelfDays;f.petCat.value=h.petCat;f.petDog.value=h.petDog;f.notes.value=h.notes||'';f.prodDate.value=today();f.qty.value=1});
dlg.querySelector('#food-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const prod=f.get('prodDate')||today();const shelf=Math.max(1,Number(f.get('shelf'))||7);
const next={id:isNew?uid():item.id,name:f.get('name').trim(),category:f.get('category'),qty:Number(f.get('qty'))||0,unit:f.get('unit').trim()||'个',prodDate:prod,expiryDate:addDays(prod,shelf),lowAt:f.get('lowAt')?Number(f.get('lowAt')):null,petCat:f.get('petCat'),petDog:f.get('petDog'),notes:f.get('notes').trim()};
update(()=>{if(isNew){S.pantry.unshift(next);addPantryHistory(next)}else{S.pantry=S.pantry.map(x=>x.id===next.id?next:x);addPantryHistory(next)}});dlg.close();toast('冰箱已更新')}}

// —— 购买清单 ——
export function renderShopping(mount){mount.innerHTML=`<section class="intro"><div><div class="eyebrow">SHOPPING LIST</div><h1>还缺什么食材？</h1><p>按本周菜单自动算缺口（扣除冰箱已有），也可以手动添加。</p></div><button class="primary" id="gen">${ico('sparkle')} 从本周菜单生成</button></section><div class="field" style="max-width:430px"><div class="ing-input"><input id="shop-name" placeholder="手动添加食材名"><input id="shop-amount" placeholder="数量（选填）"><button class="icon-button" id="shop-add" aria-label="添加">${ico('plus',15)}</button></div></div><div class="shop-list">${S.shopping.map((x,i)=>`<div class="shop-row ${x.checked?'checked':''}"><input type="checkbox" data-check="${i}" ${x.checked?'checked':''}><span><strong>${esc(x.name)}</strong>${x.amount?`<small>${esc(x.amount)}</small>`:''}</span><button class="icon-button" data-shopdel="${i}" aria-label="删除">${ico('close',13)}</button></div>`).join('')||`<div class="empty" style="grid-column:1/-1"><div>${ico('cart')}</div><h3>清单是空的</h3><p>点「从本周菜单生成」，或手动添加。</p></div>`}</div>${S.shopping.length?'<button class="text-button" id="clear-done">清空已勾选</button>':''}`;
mount.querySelector('#gen').onclick=()=>{const gen=generateShopping();if(!gen.length){toast('本周菜单里还没有安排带食材的菜');return}update(()=>{for(const g of gen){const ex=S.shopping.find(s=>s.name===g.name);if(ex)ex.amount=g.amount;else S.shopping.push({id:uid(),name:g.name,amount:g.amount,checked:false})}});toast('已按本周菜单生成缺口');renderShopping(V())};
mount.querySelector('#shop-add').onclick=()=>{const n=mount.querySelector('#shop-name').value.trim();if(!n)return;update(()=>S.shopping.push({id:uid(),name:n,amount:mount.querySelector('#shop-amount').value.trim(),checked:false}));renderShopping(V())};
mount.querySelectorAll('[data-check]').forEach(cb=>cb.onchange=()=>{update(()=>{S.shopping[Number(cb.dataset.check)].checked=cb.checked});renderShopping(V())});
mount.querySelectorAll('[data-shopdel]').forEach(b=>b.onclick=()=>{update(()=>S.shopping.splice(Number(b.dataset.shopdel),1));renderShopping(V())});
mount.querySelector('#clear-done')?.addEventListener('click',()=>{update(()=>{S.shopping=S.shopping.filter(x=>!x.checked)});renderShopping(V())})}

// —— 过期通知（页面打开时每天最多弹一次） ——
export function notifyExpiring(){const items=expiringItems();if(!items.length)return;
if('Notification'in window){if(Notification.permission==='granted'&&S.settings.lastNotify!==today()){try{new Notification('食记 · 冰箱提醒',{body:items.slice(0,3).map(p=>`${p.name}${daysUntil(p.expiryDate)<0?'已过期':daysUntil(p.expiryDate)===0?'今天到期':`还剩${daysUntil(p.expiryDate)}天`}`).join('、')+(items.length>3?' 等':'')});update(()=>S.settings.lastNotify=today())}catch{}}}}
export function requestNotify(){if('Notification'in window&&Notification.permission==='default')Notification.requestPermission()}
