// 生活板块：外出就餐 / 就餐记录 / 热量记录 / 菜品推荐
import{S,update,uid,today,addDays,monthOf,fmtDate,fmtTime,MEALS,toast,dayIntake,expiringItems,nameMatch,daysUntil,derivedLog}from'./store.js';
import{ico,esc}from'./ui.js';
import{orderDialog}from'./kitchen.js';
import{openSettings}from'./settings.js';

const V=()=>document.querySelector('#view');

// —— 外出就餐 ——
export function renderDining(mount){let q='';renderDining.cat=renderDining.cat||'全部';const draw=()=>{const cats=[...new Set(S.dining.map(d=>d.category).filter(Boolean))];const list=S.dining.filter(d=>(renderDining.cat==='全部'||d.category===renderDining.cat)&&(d.name+' '+(d.place||'')+' '+d.category).toLowerCase().includes(q));
mount.innerHTML=`<section class="intro"><div><div class="eyebrow">EATING OUT</div><h1>外出吃饭，也记下来。</h1><p>外卖、饭店、食堂都能记录热量和用时，选好店名和分类，一样可以点进本周菜单。</p></div><button class="primary" id="add-dining">${ico('plus')} 新增外出餐</button></section><div class="collection-bar"><div class="collection-title"><h2>我的外出清单</h2><span>${list.length} 条</span></div><label class="search">${ico('search',15)}<input id="d-search" placeholder="搜索店名、名称、分类…" value="${esc(q)}"><kbd>⌕</kbd></label></div><div class="filters">${['全部',...cats,...S.cats.dining].filter((c,i,arr)=>arr.indexOf(c)===i).map(c=>`<button data-dcat="${esc(c)}" class="filter ${renderDining.cat===c?'chosen':''}">${esc(c)}</button>`).join('')}<button class="filter manage" id="dining-cats">${ico('settings',13)} 编辑分类</button></div><div class="dining-grid">${list.map(d=>`<div class="dining-card"><div class="daily-top"><strong>${esc(d.name)}</strong>${d.calories?`<span class="badge fresh">${d.calories} 千卡</span>`:''}</div><span class="food-meta">${esc([d.place,d.category].filter(Boolean).join(' · '))}${d.hours||d.minutes?` · 约 ${fmtTime(d)}`:''}</span>${d.description?`<span class="food-meta" style="color:#b0b8a8">${esc(d.description)}</span>`:''}<div class="daily-actions"><button class="text-button" data-menu="${d.id}">${ico('plus',13)} 点菜</button><button class="icon-button" data-edit="${d.id}" aria-label="编辑">${ico('edit',15)}</button><button class="icon-button" data-del="${d.id}" aria-label="删除">${ico('trash',15)}</button></div></div>`).join('')||`<div class="empty" style="grid-column:1/-1"><div>${ico('utensils')}</div><h3>还没有外出记录</h3><p>把常点的外卖记下来，下次一键点进菜单。</p></div>`}</div>`;
(mount.querySelector('#add-dining')??document.createElement('button')).onclick=()=>diningDialog(null);
mount.querySelectorAll('[data-dcat]').forEach(b=>b.onclick=()=>{renderDining.cat=b.dataset.dcat;draw()});
(document.querySelector('#dining-cats')??document.createElement('button')).onclick=()=>openSettings();
(mount.querySelector('#d-search')??document.createElement('button')).oninput=e=>{q=e.target.value.toLowerCase();draw()};
mount.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>orderDialog(S.dining.find(x=>x.id===b.dataset.menu)));
mount.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>diningDialog(S.dining.find(x=>x.id===b.dataset.edit)));
mount.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(window.confirm('确定删除这条外出记录？')){update(()=>S.dining=S.dining.filter(x=>x.id!==b.dataset.del));draw()}})};draw()}

function diningDialog(d){const dlg=document.querySelector('#dialog-root');const isNew=!d;
dlg.innerHTML=`<form class="editor" id="dining-form"><div class="modal-heading"><div><span class="eyebrow">EATING OUT</span><h2>${isNew?'新增外出餐':'编辑外出餐'}</h2></div><button type="button" class="icon-button" data-close aria-label="关闭">${ico('close')}</button></div><div class="editor-content"><label class="field">菜品名称 <span class="required">*</span><input name="name" required maxlength="60" placeholder="例如：番茄牛腩面" value="${esc(d?.name||'')}"></label><div class="field-row"><label class="field">店名 / 品牌<input name="place" maxlength="40" placeholder="例如：楼下面馆" value="${esc(d?.place||'')}"></label><label class="field">分类<select name="category">${S.cats.dining.map(c=>`<option ${d?.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label class="field">热量（千卡/份）<input name="calories" type="number" min="0" max="9999" value="${d?.calories??''}"></label></div><div class="field-row"><label class="field">等餐/用时 · 小时<input name="hours" type="number" min="0" max="24" value="${d?.hours??0}"></label><label class="field">分钟<input name="minutes" type="number" min="0" max="59" value="${d?.minutes??30}"></label><label class="field">份数<input name="servings" type="number" min="1" max="20" value="${d?.servings??1}"></label></div><label class="field">备注<input name="description" maxlength="120" placeholder="口味、地址、常点搭配…" value="${esc(d?.description||'')}"></label></div><div class="modal-footer"><span></span><div><button type="button" class="secondary" data-close>取消</button><button type="submit" class="primary">${ico('check')} 保存</button></div></div></form>`;dlg.showModal();
dlg.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dlg.close());
(dlg.querySelector('#dining-form')??document.createElement('button')).onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const next={id:isNew?uid():d.id,name:f.get('name').trim(),place:f.get('place').trim(),category:f.get('category'),calories:f.get('calories')?Number(f.get('calories')):null,hours:Number(f.get('hours'))||0,minutes:Number(f.get('minutes'))||0,servings:Number(f.get('servings'))||1,description:f.get('description').trim(),image:d?.image||''};if(!next.name){toast('请填写名称');return}update(()=>{if(isNew)S.dining.unshift(next);else S.dining=S.dining.map(x=>x.id===next.id?next:x)});dlg.close();toast('已保存')}}

// —— 就餐记录 ——
const logLine=e=>{const spec=e.specs&&Object.keys(e.specs).length?' · '+Object.entries(e.specs).map(([k,v])=>v).join('/'):'';return`${e.name}${e.qty>1?` ×${e.qty}`:''}${spec}`};
export function renderJournal(mount){const cur=renderJournal.month||monthOf(today());
const DL=derivedLog();const days=Object.keys(DL).filter(d=>monthOf(d)===cur).sort();
const first=cur+'-01';const label=`${Number(cur.slice(0,4))} 年 ${Number(cur.slice(5,7))} 月`;
const prevM=monthOf(addDays(first,-1)),nextM=monthOf(addDays(first,32));const isCur=cur===monthOf(today());
const text=buildMonthText(cur,DL);
mount.innerHTML=`<section class="intro"><div><div class="eyebrow">WHAT WE ATE</div><h1>${label}，吃过什么？</h1><p>在本周菜单勾选「已吃」的每一餐自动记录在这里；按自然月清点，月初可发送上月清单。</p></div><div class="week-nav"><button class="secondary" id="j-prev">‹ ${Number(prevM.slice(5,7))} 月</button>${isCur?'':'<button class="secondary" id="j-next">下一月 ›</button>'}</div></section><div class="journal-send">${ico('mail',18)}<div><strong>${label}清单已整理好</strong><span>包含日期和菜品名，可复制后发给手机，或通过邮件应用发送。</span></div><button class="text-button" id="copy-list">${ico('copy',15)} 复制</button><button class="text-button" id="mail-list">${ico('mail',15)} 邮件发送</button></div><div class="journal-list">${days.map(d=>`<div class="journal-day"><header><strong>${fmtDate(d)} 周${'日一二三四五六'[new Date(d+'T00:00:00').getDay()]}</strong><span>共 ${dayIntake(d)} 千卡</span></header>${DL[d].map(e=>`<span class="journal-item"><em>${MEALS.find(m=>m[0]===e.meal)?.[1]||e.meal}</em>${esc(logLine(e))}${e.calories?`<small>${e.calories} 千卡</small>`:''}</span>`).join('')}</div>`).join('')||`<div class="empty"><div>${ico('calendar')}</div><h3>${label}还没有记录</h3><p>在本周菜单里勾选「已吃」，记录会自动出现在这里。</p></div>`}</div>`;
(mount.querySelector('#j-prev')??document.createElement('button')).onclick=()=>{renderJournal.month=prevM;renderJournal(V())};mount.querySelector('#j-next')?.addEventListener('click',()=>{renderJournal.month=nextM;renderJournal(V())});
(mount.querySelector('#copy-list')??document.createElement('button')).onclick=async()=>{try{await navigator.clipboard.writeText(text);toast('清单已复制，可粘贴到微信 / 备忘录发到手机')}catch{toast('复制失败，请手动选择文本')}};
(mount.querySelector('#mail-list')??document.createElement('button')).onclick=()=>{location.href=`mailto:?subject=${encodeURIComponent('饭饭 · '+label+'吃过清单')}&body=${encodeURIComponent(text)}`};}

function buildMonthText(cur,DL){const days=Object.keys(DL).filter(d=>monthOf(d)===cur).sort();let out=`【饭饭】${Number(cur.slice(0,4))}年${Number(cur.slice(5,7))}月吃过清单\n`;for(const d of days){out+=`\n${fmtDate(d)}：\n`;for(const e of DL[d])out+=`· ${MEALS.find(m=>m[0]===e.meal)?.[1]||''} ${logLine(e)}\n`}if(!days.length)out+='（这个月还没有记录）';return out}

// —— 热量记录 ——
export function renderHealth(mount){const goal=S.nutrition.goal;const t=today();const eaten=dayIntake(t);const remain=Math.max(0,goal-eaten);const pct=Math.min(100,goal?Math.round(eaten/goal*100):0);
const DL=derivedLog();const days=Object.keys(DL).filter(d=>monthOf(d)===monthOf(t)).sort().reverse();
mount.innerHTML=`<section class="intro"><div><div class="eyebrow">DAILY ENERGY</div><h1>今天的热量，心里有数。</h1><p>以本周菜单勾选「已吃」为准：勾选记入，取消勾选自动扣除。</p></div></section><div class="collection-bar" style="margin-bottom:16px"><label class="field" style="margin:0;width:260px">每日目标（千卡）<input id="goal" type="number" min="0" max="20000" value="${goal}"></label></div><div class="stat-cards"><div class="stat"><span class="stat-label">今日已摄入</span><strong>${eaten}<small> 千卡</small></strong><div class="stat-bar"><i style="width:${pct}%"></i></div></div><div class="stat"><span class="stat-label">目标剩余</span><strong>${remain}<small> 千卡</small></strong><span class="stat-sub">${goal?`${pct}% / 目标 ${goal} 千卡`:'先在下方设定每日目标'}</span></div><div class="stat"><span class="stat-label">今日记录</span><strong>${(DL[t]||[]).length}<small> 餐</small></strong><span class="stat-sub">${(S.log[t]||[]).map(logLine).slice(0,2).join('、')||'还没吃'}</span></div></div><div class="collection-bar"><div class="collection-title"><h2>每日摄入</h2><span>本月 · 目标 ${goal} 千卡</span></div></div><div class="journal-list">${days.map(d=>`<div class="journal-day"><header><strong>${fmtDate(d)} ${d===t?'· 今天':''}</strong><span>${dayIntake(d)} / ${goal} 千卡 ${goal?`(${Math.min(999,Math.round(dayIntake(d)/goal*100))}%)`:''}</span></header><div class="day-bar"><i style="width:${goal?Math.min(100,dayIntake(d)/goal*100):0}%"></i></div>${DL[d].map(e=>`<span class="journal-item"><em>${MEALS.find(m=>m[0]===e.meal)?.[1]||''}</em>${esc(logLine(e))}<small>${e.calories||0} 千卡</small></span>`).join('')}</div>`).join('')||`<div class="empty"><div>${ico('flame')}</div><h3>本月还没有摄入记录</h3><p>在本周菜单勾选「已吃」后，这里会自动累计。</p></div>`}</div>`;
(mount.querySelector('#goal')??document.createElement('button')).onchange=e=>{update(()=>S.nutrition.goal=Math.max(0,Number(e.target.value)||0));toast('目标已更新');renderHealth(V())}}

// —— 菜品推荐 ——
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
export function renderRecommend(mount){const exp=expiringItems();const eaten=dayIntake(today());const goal=S.nutrition.goal;const remain=Math.max(0,goal-eaten);
const scored=S.recipes.map(r=>{let score=0;const reasons=[];const used=[];
for(const ing of r.ingredients||[]){const p=S.pantry.find(pp=>pp.kind==='ingredient'&&nameMatch(pp.name,ing.name)&&(Number(pp.qty)||0)>0);if(!p)continue;used.push(p);const d=daysUntil(p.expiryDate);if(d<=2){score+=3;reasons.push(`消耗快过期的${p.name}`)}else score+=1}
if(used.length>=2)reasons.push(`${used.length} 种食材冰箱里都有`);
if(r.calories){if(remain&&r.calories<=remain){score+=2;reasons.push(`热量 ${r.calories} 千卡，还在今天额度内`)}else if(remain&&r.calories>remain+400)score-=2}
return{r,score,reasons:[...new Set(reasons)]}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);
const key=JSON.stringify([exp.map(p=>p.id),remain,goal]);
if(renderRecommend.key!==key||!Array.isArray(renderRecommend.queue)||!renderRecommend.queue.length){renderRecommend.queue=shuffle([...scored]);renderRecommend.key=key}
const shown=renderRecommend.queue.splice(0,6);
mount.innerHTML=`<section class="intro"><div><div class="eyebrow">SMART SUGGESTIONS</div><h1>下一餐吃什么？</h1><p>${exp.length?`优先帮你消耗${exp.slice(0,2).map(p=>esc(p.name)).join('、')}这些临期食材。`:'根据冰箱剩余量、保质期和今天的热量余量来推荐。'}</p></div><div class="detail-tools"><button class="secondary" id="rec-refresh">${ico('sparkle')} 换一批</button></div></section><div class="rec-grid">${shown.map(({r,reasons})=>`<article class="recipe-card"><div class="card-image">${r.image?`<img src="${esc(r.image)}" alt="${esc(r.name)}" loading="lazy" onerror="this.style.display='none'">`:''}<span class="image-placeholder">${ico('bowl')}</span><span class="category-badge">${esc(r.category||'')}</span></div><div class="card-content"><h3>${esc(r.name)}</h3><p>${esc(reasons.join(' · ')||'冰箱里有它的食材')}</p><div class="card-meta"><span>${ico('clock',12)} ${fmtTime(r)}</span>${r.calories?`<span>${ico('flame',12)} ${r.calories} 千卡</span>`:''}</div><button class="text-button" data-menu="${r.id}" style="margin-top:10px">${ico('plus',14)} 点这份菜</button></div></article>`).join('')||`<div class="empty" style="grid-column:1/-1"><div>${ico('sparkle')}</div><h3>暂时没有特别的推荐</h3><p>往冰箱里添点食材，或给菜谱填上食材和热量，推荐会更准。</p></div>`}</div>`;
(mount.querySelector('#rec-refresh')??document.createElement('button')).onclick=()=>{renderRecommend.key='';renderRecommend(V())};
mount.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>orderDialog(S.recipes.find(x=>x.id===b.dataset.menu)))}
