// 菜谱板块：烹饪菜与零食速食共用（列表 / 详情 / 编辑器）
import{S,update,uid,fmtTime,today,toast}from'./store.js';
import{ico,esc,fileToDataUrl}from'./ui.js';
import{orderDialog}from'./kitchen.js';
import{openSettings}from'./settings.js';

let type='dish',selected='',query='',category='全部';
export const setType=t=>{type=t;category='全部';query=''};
export function selectRecipe(id){const r=S.recipes.find(x=>x.id===id);if(!r)return;type=r.type;selected=id;location.hash='#/recipes'}
const V=()=>document.querySelector('#view');
function rerender(){render(V())}
export function filteredRecipes(){return S.recipes.filter(r=>r.type===type&&(category==='全部'||r.category===category)&&[r.name,r.ingredients.map(i=>i.name+' '+(i.amount||''))].join(' ').toLowerCase().includes(query.toLowerCase()))}
export function recipeCats(){return[...new Set([...S.cats[type]||[],...S.recipes.filter(r=>r.type===type).map(r=>r.category).filter(Boolean)])]}

const cardSub=r=>(r.ingredients||[]).map(i=>i.name).slice(0,3).join(' · ')||'点击查看做法详情';
const cardSpecs=r=>(r.specs||[]).filter(sp=>sp.enabled&&sp.name).map(sp=>sp.name).join(' / ');

function card(r){return`<article class="recipe-card ${selected===r.id?'selected':''}"><button class="card-main" data-select="${r.id}" aria-label="查看${esc(r.name)}"><div class="card-image">${r.image?`<img src="${esc(r.image)}" alt="${esc(r.name)}" loading="lazy" onerror="this.style.display='none'">`:''}<span class="image-placeholder">${ico('leaf')}</span><span class="category-badge">${esc(r.category||'未分类')}</span></div><div class="card-content"><h3>${esc(r.name)}</h3><p>${esc(cardSub(r))}</p><div class="card-meta"><span>${ico('clock',12)} ${fmtTime(r)}</span>${r.calories?`<span>${ico('flame',12)} ${r.calories} 千卡/份</span>`:''}${cardSpecs(r)?`<span class="meta-specs">${esc(cardSpecs(r))}</span>`:''}</div></div></button><button class="card-order" data-order="${r.id}" aria-label="点菜${esc(r.name)}" title="点菜">${ico('plus',16)}</button></article>`}

function detail(r){const groups=(r.specs||[]).filter(sp=>sp.enabled&&sp.name);
return`<div class="detail-heading"><span>详情</span><span class="detail-tools"><button class="text-button" id="order">${ico('plus',15)} 点菜</button><button class="text-button" id="edit">${ico('edit',15)} 编辑</button></span></div><div class="detail-image">${r.image?`<img src="${esc(r.image)}" alt="${esc(r.name)}" onerror="this.style.display='none'">`:''}<span class="image-placeholder">${ico('leaf')}</span><span class="detail-image-label">FROM MY KITCHEN</span></div><div class="detail-body"><div class="detail-tags"><span>${esc(r.category||'未分类')}</span><span>${ico('clock',12)} ${fmtTime(r)}</span><span>${ico('people',12)} ${esc(r.servings)} 人份</span>${r.calories?`<span>${ico('flame',12)} ${r.calories} 千卡/份</span>`:''}${r.prep?`<span class="tag-spec">${ico('clock',11)} 提前准备</span>`:''}${groups.map(g=>`<span class="tag-spec">${esc(g.name)}</span>`).join('')}</div><h2>${esc(r.name)}</h2><section class="ingredients"><h3>${ico('leaf',15)} 准备食材 <small>${esc(r.servings)} 人份</small></h3><div class="ingredient-list">${(r.ingredients||[]).map(i=>`<div><strong>${esc(i.name)}</strong><em>${esc(i.amount||'')}</em></div>`).join('')||'<p class="muted">还没有填写食材</p>'}</div></section><section class="steps"><h3>${ico('book',15)} ${type==='snack'?'制作方法':'开始烹饪'} <small>${(r.steps||[]).length} 个步骤</small></h3>${(r.steps||[]).map((s,i)=>`<div class="step"><span>${String(i+1).padStart(2,'0')}</span><div class="step-body"><div class="step-line"><p>${esc(s.text)}</p></div>${s.image?`<div class="step-line"><img class="step-image" src="${esc(s.image)}" alt="步骤${i+1}配图" loading="lazy"></div>`:''}</div></div>`).join('')}</section><button class="menu-toggle" id="order-big">${ico('plus',14)} 点这份菜 · 选择份数、规格和日期</button></div>`}

export function render(mount){const list=filteredRecipes();if(!list.some(r=>r.id===selected))selected=list[0]?.id||'';const r=S.recipes.find(x=>x.id===selected);
mount.innerHTML=`<section class="intro"><div><div class="eyebrow">${type==='dish'?'A LITTLE KITCHEN, A LOT OF LOVE':'SNACKS & INSTANT FOOD'}</div><h1>${type==='dish'?'把好味道，留下来。':'零食和速食，也值得记录。'}</h1><p>${type==='dish'?'记录拿手好菜，收藏日常灵感，慢慢写成自己的食谱。':'和菜谱一样记录热量、时长，点菜后勾选已吃就会扣减冰箱库存。'}</p></div><button class="primary" id="add">${ico('plus')} 新建${type==='dish'?'菜谱':'零食速食'}</button></section><div class="collection-bar"><div class="collection-title"><div class="type-tabs" role="tablist"><button role="tab" aria-selected="${type==='dish'}" data-type="dish" class="${type==='dish'?'chosen':''}">烹饪菜</button><button role="tab" aria-selected="${type==='snack'}" data-type="snack" class="${type==='snack'?'chosen':''}">零食速食</button></div><span>${list.length} 条用心记录</span></div><label class="search">${ico('search',15)}<input id="search" placeholder="搜索菜名、食材…" value="${esc(query)}" aria-label="搜索"><kbd>⌕</kbd></label></div><div class="filters">${['全部',...recipeCats()].map(c=>`<button data-category="${esc(c)}" class="filter ${category===c?'chosen':''}">${esc(c)}${c==='全部'?`<span>${S.recipes.filter(x=>x.type===type).length}</span>`:''}</button>`).join('')}<button class="filter manage" id="manage-cats">${ico('settings',13)} 分类与规格</button></div><div class="recipe-layout"><section class="cards" aria-label="列表">${list.map(card).join('')||`<div class="empty"><div>${ico('book')}</div><h3>${query?'没有找到':'这里还没有记录'}</h3><p>${query?'换个菜名或食材试试。':'点击右上角「新建」记录第一条。'}</p></div>`}${list.length?`<button class="new-card" id="add-card"><span>${ico('plus')}</span><strong>新的灵感</strong><small>把新的美味记下来</small></button>`:''}</section><aside class="detail">${r?detail(r):`<div class="detail-empty">${ico('leaf')}<p>每道好味道，都值得记下来。</p></div>`}</aside></div>`;bind(mount,r)}

function bind(mount,r){mount.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{setType(b.dataset.type);rerender()});mount.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;rerender()});mount.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{selected=b.dataset.select;rerender()});mount.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>orderDialog(S.recipes.find(x=>x.id===b.dataset.order)));const s=mount.querySelector('#search');s.oninput=()=>{const pos=s.selectionStart;query=s.value;rerender();const i2=V().querySelector('#search');i2.focus();i2.setSelectionRange(pos,pos)};mount.querySelector('#add').onclick=()=>openRecipeEditor(null,type);mount.querySelector('#add-card').onclick=()=>openRecipeEditor(null,type);mount.querySelector('#manage-cats').onclick=()=>openSettings();if(!r)return;mount.querySelector('#edit').onclick=()=>openRecipeEditor(r,type);mount.querySelector('#order').onclick=()=>orderDialog(r);mount.querySelector('#order-big').onclick=()=>orderDialog(r)}

// —— 编辑器 ——
export function openRecipeEditor(r,typeOf){type=typeOf;const isNew=!r;const draft={image:r?.image||'',ingredients:(r?.ingredients||[]).map(x=>({...x})),steps:(r?.steps||[{text:'',image:''}]).map(x=>({...x})),specs:(r?.specs||[]).map(sp=>({name:sp.name,options:[...(sp.options||[])],enabled:sp.enabled!==false}))};
const dlg=document.querySelector('#dialog-root');const cats=[...new Set([...S.cats[type]||[],...(r?.category?[r.category]:[])])];
dlg.innerHTML=`<form id="recipe-form" class="editor"><div class="modal-heading"><div><span class="eyebrow">YOUR NEXT SIGNATURE DISH</span><h2>${isNew?`记录${type==='dish'?'一道新菜':'一份零食/速食'}`:'编辑记录'}</h2></div><button type="button" class="icon-button" data-close aria-label="关闭">${ico('close')}</button></div><div class="editor-content"><label class="field">名称 <span class="required">*</span><input name="name" required maxlength="60" placeholder="${type==='dish'?'例如：妈妈的红烧肉':'例如：无糖酸奶'}" value="${esc(r?.name||'')}"></label><div class="field-row four"><label class="field">分类<select name="category">${cats.map(c=>`<option ${r?.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label class="field">小时<input name="hours" type="number" min="0" max="99" value="${r?.hours??0}"></label><label class="field">分钟<input name="minutes" type="number" min="0" max="59" value="${r?.minutes??30}"></label><label class="field">人份<input name="servings" type="number" min="1" max="100" value="${r?.servings||1}"></label></div><label class="field">热量（千卡 / 份）<span class="optional">选填，填了才能统计每日摄入</span><input name="calories" type="number" min="0" max="9999" placeholder="例如：520" value="${r?.calories??''}"></label><label class="prep-line"><input type="checkbox" name="prep" ${r?.prep?'checked':''}> 这道菜有需要提前准备的步骤（前一天 18:00 提醒）</label><div class="field">点菜规格 <span class="optional">本菜谱独立设置；勾选启用，名称与选项随时改</span><div id="spec-fields">${draft.specs.map(specRow).join('')}</div><button class="add-step" type="button" id="add-spec">${ico('plus')} 添加规格</button></div><div class="field">配图 <span class="optional">选填 · 列表中以 1:1 展示 · 自动压缩保存</span><label class="upload-area" for="image-input"><img id="image-preview" alt="配图预览" ${draft.image?`src="${esc(draft.image)}"`:'hidden'}><span>${ico('upload')}<strong>点击上传照片</strong><small>最长边 1400px</small></span></label><input type="file" id="image-input" accept="image/jpeg,image/png,image/webp" hidden><button type="button" id="remove-image" class="text-button" ${draft.image?'':'hidden'}>移除图片</button></div><div class="field">准备食材 <span class="optional">名称 + 用量，用于生成购买清单和扣减库存</span><div id="ing-fields">${draft.ingredients.map(ingField).join('')||ingField()}</div><button class="add-step" type="button" id="add-ing">${ico('plus')} 添加食材</button></div><div class="field">做法步骤 <span class="optional">可配图</span><div id="step-fields">${draft.steps.map((s,i)=>stepField(s,i)).join('')}</div><button class="add-step" type="button" id="add-step">${ico('plus')} 添加步骤</button></div></div><div class="modal-footer">${isNew?'<span class="muted">好味道，从这一次记录开始。</span>':`<button type="button" class="danger-button" id="delete-recipe">${ico('trash',14)} 删除</button>`}<div><button type="button" class="secondary" data-close>取消</button><button type="submit" class="primary">${ico('check')} 保存</button></div></div></form>`;dlg.showModal();
const close=()=>dlg.close();dlg.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);
dlg.querySelector('#add-spec').onclick=()=>dlg.querySelector('#spec-fields').insertAdjacentHTML('beforeend',specRow());dlg.querySelectorAll('.spec-del').forEach(b=>b.onclick=()=>b.closest('.spec-row').remove());
const renumber=()=>{dlg.querySelectorAll('#step-fields .step-input').forEach((row,i)=>{row.querySelector('.num').textContent=String(i+1).padStart(2,'0');const inp=row.querySelector('.step-image-input');if(inp)inp.dataset.idx=i})};
dlg.querySelector('#add-ing').onclick=()=>dlg.querySelector('#ing-fields').insertAdjacentHTML('beforeend',ingField());dlg.querySelector('#add-step').onclick=()=>{const n=dlg.querySelectorAll('#step-fields .step-input').length;dlg.querySelector('#step-fields').insertAdjacentHTML('beforeend',stepField(undefined,n));renumber()};
dlg.querySelectorAll('.ing-remove').forEach(b=>b.onclick=()=>b.closest('.ing-input').remove());dlg.querySelectorAll('.step-remove').forEach(b=>b.onclick=()=>{if(dlg.querySelectorAll('#step-fields .step-input').length===1){toast('请至少保留一个步骤');return}b.closest('.step-input').remove();renumber()});
fileToDataUrl(dlg.querySelector('#image-input'),url=>{draft.image=url;const img=dlg.querySelector('#image-preview');img.src=url;img.hidden=false;dlg.querySelector('#remove-image').hidden=false});dlg.querySelector('#remove-image').onclick=()=>{draft.image='';dlg.querySelector('#image-preview').hidden=true;dlg.querySelector('#image-input').value='';dlg.querySelector('#remove-image').hidden=true};
dlg.querySelectorAll('.step-image-input').forEach(inp=>fileToDataUrl(inp,url=>{const idx=Number(inp.dataset.idx);if(draft.steps[idx])draft.steps[idx].image=url;const img=inp.closest('.step-input').querySelector('.step-image-preview');img.src=url;img.hidden=false},800,0.7));
dlg.querySelector('#delete-recipe')?.addEventListener('click',()=>{if(window.confirm(`确定删除「${r.name}」？此操作无法撤销。`)&&update(()=>{S.recipes=S.recipes.filter(x=>x.id!==r.id)})){dlg.close();rerender();toast('已删除')}});
dlg.querySelector('#recipe-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const name=f.get('name').trim();const steps=[...dlg.querySelectorAll('#step-fields .step-input')].map((row,i)=>({text:row.querySelector('textarea').value.trim(),image:draft.steps[i]?.image||''})).filter(s=>s.text);const ingredients=[...dlg.querySelectorAll('#ing-fields .ing-input')].map(row=>({name:row.querySelector('.ing-name').value.trim(),amount:row.querySelector('.ing-amount').value.trim()})).filter(i=>i.name);const specs=[...dlg.querySelectorAll('#spec-fields .spec-row')].map(row=>({name:row.querySelector('.spec-name').value.trim(),options:row.querySelector('.spec-opts').value.split(/[，,、]/).map(x=>x.trim()).filter(Boolean),enabled:row.querySelector('.spec-en').checked})).filter(sp=>sp.name&&sp.options.length);if(!name){toast('请填写名称');return}
const next={id:isNew?uid():r.id,type,name,category:f.get('category'),hours:Number(f.get('hours'))||0,minutes:Number(f.get('minutes'))||0,servings:Number(f.get('servings'))||1,calories:f.get('calories')?Number(f.get('calories')):null,image:draft.image,ingredients,steps,favorite:r?.favorite||false,specs,prep:f.get('prep')==='on'};
update(()=>{if(isNew)S.recipes.unshift(next);else S.recipes=S.recipes.map(x=>x.id===next.id?next:x)});selected=next.id;dlg.close();rerender();toast('已保存')}}

function ingField(i={name:'',amount:''}){return`<div class="ing-input"><input class="ing-name" placeholder="食材名，如：番茄" value="${esc(i.name)}"><input class="ing-amount" placeholder="用量，如：2 个" value="${esc(i.amount)}"><button type="button" class="icon-button ing-remove" aria-label="删除食材">${ico('close',15)}</button></div>`}
function specRow(sp={name:'',options:[],enabled:true}){return`<div class="spec-row"><label class="prep-check"><input type="checkbox" class="spec-en" ${sp.enabled?'checked':''}> 启用</label><input class="spec-name" placeholder="规格名，如：口味" value="${esc(sp.name)}"><input class="spec-opts" placeholder="选项，逗号分隔，如：清淡,微辣" value="${esc((sp.options||[]).join('，'))}"><button type="button" class="icon-button spec-del" aria-label="删除规格">${ico('close',15)}</button></div>`}
function stepField(s={text:'',image:''},idx=0){return`<div class="step-input"><span class="num">${String(idx+1).padStart(2,'0')}</span><div class="step-edit"><textarea aria-label="步骤" rows="2" placeholder="写下这一步的做法…">${esc(s.text)}</textarea><div class="step-tools"><label class="step-image-btn">${ico('upload',14)} 配图<input type="file" class="step-image-input" data-idx="${idx}" accept="image/jpeg,image/png,image/webp" hidden></label></div><img class="step-image-preview" alt="步骤配图" ${s.image?`src="${esc(s.image)}"`:'hidden'}></div><button type="button" class="icon-button step-remove" aria-label="删除步骤">${ico('close',15)}</button></div>`}
