// 设置：菜单分类（四组）+ 规格分类（口味/忌口等，可自定义组与选项）
import{S,update,uid,toast}from'./store.js';
import{ico,esc}from'./ui.js';

const GROUPS=[['dish','菜单分类'],['drink','水吧分类'],['fridge','冰箱食材分类'],['fridgeSnack','冰箱速食零食分类'],['diningVenue','外出就餐大分类'],['daily','日用品分类']];

export function openSettings(onDone){if(!S.cats.diningCats||typeof S.cats.diningCats!=='object'||Array.isArray(S.cats.diningCats))S.cats.diningCats={};
const dlg=document.querySelector('#dialog-root');
const chipList=(arr,group,venue='')=>`${(arr||[]).map((c,i)=>`<span class="cat-chip"><input value="${esc(c)}" data-i="${i}" aria-label="重命名分类 ${esc(c)}"><button class="icon-button cat-remove" data-i="${i}" aria-label="删除分类 ${esc(c)}">${ico('close',12)}</button></span>`).join('')}<span class="cat-chip cat-add"><input placeholder="新增分类" aria-label="新增分类"><button class="icon-button" data-add aria-label="添加分类">${ico('plus',13)}</button></span>`;
const catSection=GROUPS.map(([key,label])=>`<div class="field"><span class="cat-label">${label}</span><div class="cat-list" data-group="${key}">${chipList(S.cats[key],key)}</div></div>`).join('')+(S.cats.diningVenue||[]).map(v=>`<div class="field"><span class="cat-label">${esc(v)}小分类</span><div class="cat-list" data-group="diningCats" data-venue="${esc(v)}">${chipList((S.cats.diningCats||{})[v]||['其他'],'diningCats',v)}</div></div>`).join('');
dlg.innerHTML=`<div class="editor"><div class="modal-heading"><div><span class="eyebrow">MAKE IT YOURS</span><h2>分类管理</h2></div><button class="icon-button" data-close aria-label="关闭">${ico('close')}</button></div><div class="editor-content">${catSection}<p class="muted">删除分类/规格不会删除内容本身；改名会同步更新所有使用它的记录。</p></div><div class="modal-footer"><span></span><div><button class="secondary" data-close>关闭</button></div></div></div>`;
dlg.showModal();
dlg.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{dlg.close();onDone?.()});
// —— 菜单分类编辑 ——
dlg.querySelectorAll('.cat-list[data-group]').forEach(list=>{const key=list.dataset.group;const venue=list.dataset.venue||'';
const arr=()=>key==='diningCats'?(S.cats.diningCats[venue]||=[]):S.cats[key];
list.querySelectorAll('.cat-chip input').forEach(inp=>{if(inp.closest('.cat-add'))return;inp.onchange=()=>{const i=Number(inp.dataset.i);const old=arr()[i];const nv=inp.value.trim();if(!nv||nv===old)return;if(arr().includes(nv)){toast('分类已存在');inp.value=old;return}update(()=>{arr()[i]=nv;if(key==='dish'||key==='drink')S.recipes.forEach(r=>{if(r.type===key&&r.category===old)r.category=nv});if(key==='fridge')S.pantry.forEach(p=>{if(p.kind!=='snack'&&p.category===old)p.category=nv});if(key==='fridgeSnack')S.pantry.forEach(p=>{if(p.kind==='snack'&&p.category===old)p.category=nv});if(key==='diningVenue'){if(S.cats.diningCats[old]){S.cats.diningCats[nv]=S.cats.diningCats[old];delete S.cats.diningCats[old]}S.dining.forEach(d=>{if(d.venue===old)d.venue=nv})}if(key==='diningCats')S.dining.forEach(d=>{if(d.venue===venue&&d.category===old)d.category=nv});if(key==='daily')S.daily.forEach(d=>{if(d.category===old)d.category=nv});S.shopping.forEach(s=>{if(s.category===old)s.category=nv})});if(key==='diningVenue')openSettings(onDone);toast('分类已重命名')}});
list.querySelectorAll('.cat-remove').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.i);if(arr().length<=1){toast('至少保留一个分类');return}update(()=>{const old=arr()[i];const next=arr().filter((_,j)=>j!==i);const first=next[0];if(key==='diningCats')S.cats.diningCats[venue]=next;else S.cats[key]=next;if(key==='dish'||key==='drink')S.recipes.forEach(r=>{if(r.type===key&&r.category===old)r.category=first});if(key==='fridge')S.pantry.forEach(p=>{if(p.kind!=='snack'&&p.category===old)p.category=first});if(key==='fridgeSnack')S.pantry.forEach(p=>{if(p.kind==='snack'&&p.category===old)p.category=first});if(key==='diningVenue'){S.dining.forEach(d=>{if(d.venue===old)d.venue=first});delete S.cats.diningCats[old]}if(key==='diningCats')S.dining.forEach(d=>{if(d.venue===venue&&d.category===old)d.category=first});if(key==='daily')S.daily.forEach(d=>{if(d.category===old)d.category=first});S.shopping.forEach(s=>{if(s.category===old)s.category=first})});openSettings(onDone);toast('分类已删除')});
(list.querySelector('[data-add]')??document.createElement('button')).onclick=()=>{const inp=list.querySelector('.cat-add input');const nv=inp.value.trim();if(!nv)return;if(arr().includes(nv)){toast('分类已存在');return}update(()=>{arr().push(nv);if(key==='diningVenue')(S.cats.diningCats||(S.cats.diningCats={}))[nv]=['其他']});openSettings(onDone)}});

}